# Generated by Django 2.2.1 on 2019-05-02 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='purse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coins', to='api.Purse'),
        ),
    ]
